name: alcione_scouting
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+11

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- FIREBASE AGGIORNATO (Fix definitivo per Xcode 16 e Non-Modular Headers) ---
  firebase_core: 4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0

  # --- ALTRE DIPENDENZE ---
  pdf: ^3.10.8
  printing: ^5.14.3
  shared_preferences: ^2.3.5
  flutter_slidable: ^3.1.2
  fl_chart: ^0.70.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_alcione.png"

flutter:
  uses-material-design: true
  assets:
    - assets/