platform :ios, '15.0'

# Importa le configurazioni di Flutter
def flutter_install_all_ios_pods(ios_application_path = nil)
  native_additions_path = File.join(ios_application_path, 'Flutter', 'podhelper.rb')
  abort "podhelper.rb non trovato" unless File.exists?(native_additions_path)
  require native_additions_path
  flutter_ios_podfile_setup
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end