platform :ios, '15.0'

# Caricamento del podhelper
podhelper_path = File.join(File.dirname(__FILE__), 'Flutter', 'podhelper.rb')
require podhelper_path

# --- TRUCCO PER CODEMAGIC ---
# Se il file .metadata manca o è vuoto, creiamone uno valido prima che Flutter lo cerchi
metadata_path = File.join(File.dirname(__FILE__), '.metadata')
if !File.exist?(metadata_path) || File.read(metadata_path).strip.empty?
  File.write(metadata_path, '{"version":"1.0.0","project_type":"app"}')
end
# ----------------------------

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(__FILE__)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['DEFINES_MODULE'] = 'YES'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end