name: iOS Build Test

on:
  push:
    branches: [ main ]

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Scarica il codice
        uses: actions/checkout@v4

      - name: Installa Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.0' # Assicurati che sia la versione che usi tu

      - name: Installa dipendenze Dart
        run: flutter pub get

      - name: Installa certificati Apple
        uses: apple-actions/import-codesigning-certs@v3
        with:
          p12-file-base64: ${{ secrets.IOS_P12_BASE64 }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}

      - name: Installa Provisioning Profile
        uses: apple-actions/download-provisioning-profiles@v3
        with:
          bundle-id: 'it.alcione.scouting' # <--- SOSTITUISCI CON IL TUO BUNDLE ID REALE
          profile-type: 'IOS_APP_STORE'
          provisioning-profile-base64: ${{ secrets.IOS_PROVISION_PROFILE_BASE64 }}

      - name: Compila IPA per TestFlight
        run: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
